-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
--  _   _                  _                 _           --
-- | | | |_   _ _ __  _ __| | __ _ _ __   __| |          --
-- | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` |          --
-- |  _  | |_| | |_) | |  | | (_| | | | | (_| |          --
-- |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_|          --
--        |___/|_|                                       --
--                                                       --
--   CONVERTED HYPRLAND LUA CONFIGURATION                --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- Remove warning
hl.config({ autogenerated = false })

------------------
---- MONITORS ----
------------------
-- monitor=eDP-1,1920x1080@60,auto,1.5
hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60",
    position = "auto",
    scale = 1.5,
})

-------------------
---- AUTOSTART ----
-------------------
hl.on("hyprland.start", function ()
    hl.dsp.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.dsp.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.dsp.exec_cmd("waybar")
    hl.dsp.exec_cmd("hyprpaper")
    hl.dsp.exec_cmd("dunst")
    -- New Essential Utilities
    hl.dsp.exec_cmd("hypridle")
    hl.dsp.exec_cmd("/usr/libexec/polkit-gnome-authentication-agent-1")
    hl.dsp.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.dsp.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.dsp.exec_cmd("nm-applet --indicator")
    hl.dsp.exec_cmd("blueman-applet")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------
hl.env("OZONE_PLATFORM", "wayland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct") -- Enables uniform Qt/GTK theming
hl.env("XCURSOR_SIZE", "24")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("GDK_SCALE", "1")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("APPIMAGELAUNCHER_DISABLE", "1")
hl.env("OZONE_PLATFORM", "wayland")

-----------------------
---- LOOK AND FEEL ----
-----------------------
hl.config({
    input = {
        kb_layout = "us",
        follow_mouse = 1,
        touchpad = {
            natural_scroll = false
        },
        sensitivity = 0
    },

    general = {
        gaps_in = 3,
        gaps_out = 0,
        border_size = 1,
        col = {
            active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
        layout = "dwindle",
        resize_on_border = true
    },

    decoration = {
        rounding = 5,
        active_opacity = 1.0,
        blur = {
            enabled = true,
            size = 3,
            passes = 1
        },
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)"
        }
    },

    animations = {
        enabled = true,
    },

    dwindle = {
        preserve_split = true
    },

    xwayland = {
        force_zero_scaling = true
    },

    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        enable_swallow = true,
        swallow_regex = "^(kitty)$"
    }
})

-- Animations
hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.animation({ leaf = "windows", enabled = true, speed = 7, bezier = "myBezier" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 7, bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "border", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 8, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 7, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 6, bezier = "default" })

-- Gestures
hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

----------------------
---- WINDOW RULES ----
----------------------
-- Float common utility applications
hl.window_rule({ name = "float-pavucontrol", match = { class = "pavucontrol" }, float = true })
hl.window_rule({ name = "float-blueman", match = { class = "blueman-manager" }, float = true })
hl.window_rule({ name = "float-nmconnection", match = { class = "nm-connection-editor" }, float = true })
hl.window_rule({ name = "float-calculator", match = { class = "org.gnome.Calculator" }, float = true })
hl.window_rule({ name = "float-file-roller", match = { class = "file-roller" }, float = true })
-- Keep browser Picture-in-Picture mode floating and pinned to all workspaces
hl.window_rule({ name = "float-pip", match = { title = "Picture-in-Picture" }, float = true, pin = true })

-- App to Workspace Bindings
hl.window_rule({ name = "workspace-firefox", match = { class = "firefox" }, workspace = "1" })
hl.window_rule({ name = "workspace-discord", match = { class = "discord" }, workspace = "4" })
hl.window_rule({ name = "workspace-webcord", match = { class = "WebCord" }, workspace = "4" })
hl.window_rule({ name = "workspace-vesktop", match = { class = "vesktop" }, workspace = "4" })
hl.window_rule({ name = "workspace-spotify", match = { class = "Spotify" }, workspace = "5" })

---------------------
---- KEYBINDINGS ----
---------------------
local mainMod = "SUPER"

-- Actions
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("~/.config/hypr/powermenu.sh"))
hl.bind(mainMod .. " + ESCAPE", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("nautilus"))
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen())
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("rofi -show drun"))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + O", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("firefox"))
hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd("pkill -USR2 waybar"))
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("cliphist list | rofi -dmenu -p 'Clipboard' | cliphist decode | wl-copy"))

-- Scratchpad (Special Workspace)
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Night Light (Toggle blue light filter)
hl.bind(mainMod .. " + SHIFT + N", hl.dsp.exec_cmd("pkill wlsunset || wlsunset -t 4500"))

-- Emoji & Calculator Pickers
hl.bind(mainMod .. " + PERIOD", hl.dsp.exec_cmd("rofimoji"))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd("rofi -show calc -modi calc -no-show-match -no-sort"))

-- Game Mode (Toggle animations & blur)
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd("~/.config/hypr/gamemode.sh"))

-- Move focus
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))

-- Workspaces
for i = 1, 10 do
    local key = i % 10 -- 10 maps to 0
    hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Scroll through workspaces
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Mouse binds
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Volume Control
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+"), { repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))

-- Brightness Control
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 5%+"), { repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"), { repeating = true })

-- Media Player Controls
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))
hl.bind("XF86AudioStop", hl.dsp.exec_cmd("playerctl stop"))

-- Resize Window Bindings
-- Note: Fixed syntax error from old config, now properly using SUPER
-- (Disabled SUPER + R for resizeactive to free it up for Rofi)
-- hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("hyprctl dispatch resizeactive"))
hl.bind(mainMod .. " + SHIFT + Left", hl.dsp.exec_cmd("hyprctl dispatch resize -10 0"))
hl.bind(mainMod .. " + SHIFT + Right", hl.dsp.exec_cmd("hyprctl dispatch resize 10 0"))
hl.bind(mainMod .. " + SHIFT + Up", hl.dsp.exec_cmd("hyprctl dispatch resize 0 -10"))
hl.bind(mainMod .. " + SHIFT + Down", hl.dsp.exec_cmd("hyprctl dispatch resize 0 10"))

-- Screenshots (Saves to ~/Pictures AND copies to clipboard)
hl.bind("Print", hl.dsp.exec_cmd([[grim - | tee ~/Pictures/screenshot-$(date +%s).png | wl-copy -t image/png]]))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd([[grim -g "$(slurp)" - | tee ~/Pictures/screenshot-$(date +%s).png | wl-copy -t image/png]]))
hl.bind("ALT + Print", hl.dsp.exec_cmd([[grim -g "$(hyprctl clients -j | jq -r '.[] | select(.focused == true) | \"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])\"')" - | tee ~/Pictures/screenshot-$(date +%s).png | wl-copy -t image/png]]))
hl.bind(mainMod .. " + G", hl.dsp.exec_cmd([[grim - | tee ~/Pictures/screenshot-$(date +%s).png | wl-copy -t image/png]]))
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd([[grim -g "$(slurp)" - | tee ~/Pictures/screenshot-$(date +%s).png | wl-copy -t image/png]]))
