# Execute your favorite apps at launch
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user start xdg-desktop-portal-hyprland
exec-once = waybar > /dev/null 2>&1
exec-once = hyprpaper
exec-once = dunst